registry: registry.sigma.fr
repository: kubeception
version: v1.26.0

apiserver:
  ingress:
    hostname: example-cluster.mks.scaleship.io
  oidc:
    issuer: https://accounts.google.com
    algs: RS512
    client: example-client-key
    username:
      name: email
      prefix: oidc
    groups:
      name: groups
      prefix: oidc
  konnectivity:
    agent:
      ingress:
        hostname: konnectivity-agent.example-cluster.mks.scaleship.io
    server:
      ingress:
        hostname: konnectivity-server.example-cluster.mks.scaleship.io

etcd:
  image: quay.io/coreos/etcd:v3.5.7
  storage:
    className: ""
    size: 5Gi

dashboard:
  image: kubernetesui/dashboard:v2.7.0
  ingress:
    hostname: dashboard.example-cluster.mks.scaleship.io
