registry: registry.scaleship.io
repository: kubeception

apiserver:
  advertise:
    public:
      ingress:
        labels: []
        annotations: []
        className: ""
        hostname: api.kube-9ni825sw.mks.scaleship.io
    internal:
      ingress:
        labels: []
        annotations: []
        className: ""
        hostname: kube-9ni825sw.mks.scaleship.io
  oidc:
    issuer: https://accounts.scaleship.io/oidc/v1
    algs: RS512
    secretName: oidc
    username:
      name: email
      prefix: oidc
    groups:
      name: groups
      prefix: oidc
  konnectivity:
    version: v0.0.37
    agent:
      ingress:
        labels: []
        annotations: []
        className: ""
        hostname: konnectivity-agent.kube-9ni825sw.mks.scaleship.io
    server:
      ingress:
        labels: []
        annotations: []
        className: ""
        hostname: konnectivity-server.kube-9ni825sw.mks.scaleship.io

etcd:
  version: v3.5.9
  storage:
    className: ""
    size: 5Gi

dashboard:
  version: v2.7.0
  ingress:
    labels: []
    annotations: []
    className: ""
    hostname: dashboard.kube-9ni825sw.mks.scaleship.io
    issuer: letsencrypt-staging
