apiserver:
  image: registry.k8s.io/kube-apiserver:v1.26.0
  ingress:
    hostname: example-cluster.mks.scaleship.io
  oidc:
    issuer: https://accounts.google.com
    algs: RS512
    client: example-client-key
    username: email
    groups: groups
    claim: "key=value"

etcd:
  image: quay.io/coreos/etcd:v3.5.7
  storage:
    className: ""
    size: 5Gi

kubeconfig:
  image: registry.sigma.fr/library/kubeception-kubeconfigs:v1.26.2

ControllerManager:
  image: registry.k8s.io/kube-controller-manager:v1.26.0

dashboard:
  image: kubernetesui/dashboard:v2.7.0
  ingress:
    hostname: dashboard.example-cluster.mks.scaleship.io