registry: registry.sigma.fr
repository: kubeception
version: v1.26.0

apiserver:
  ingress:
    hostname: example-cluster.mks.scaleship.io
  oidc:
    issuer: https://access-recette.sigma.fr/sigma-recette-oauth2/v1
    algs: RS512
    secretName: oidc
    username:
      name: email
      prefix: oidc
    groups:
      name: groups
      prefix: oidc
  konnectivity:
    version: v0.0.37
    agent:
      ingress:
        hostname: konnectivity-agent.example-cluster.mks.scaleship.io
    server:
      ingress:
        hostname: konnectivity-server.example-cluster.mks.scaleship.io

etcd:
  version: v3.5.9
  storage:
    className: ""
    size: 5Gi

dashboard:
  version: v2.7.0
  ingress:
    hostname: dashboard.example-cluster.mks.scaleship.io
    issuer: letsencrypt-staging
