kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: apiserver-public
  annotations:
    ingress.kubernetes.io/proxy-body-size: '0'
    route.openshift.io/termination: "reencrypt"
    route.openshift.io/destination-ca-certificate-secret: "kubernetes-ca"
spec:
  rules:
    - host: {{ .Values.apiserver.advertise.public.ingress.hostname }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: apiserver
                port:
                  number: 443 
  tls:
    - secretName: kube-apiserver-external
      hosts:
        - {{ .Values.apiserver.advertise.public.ingress.hostname }}