kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: apiserver-internal
  annotations:
    ingress.kubernetes.io/proxy-body-size: '0'
    ingress.kubernetes.io/ssl-redirect: 'true'
    route.openshift.io/termination: "passthrough"
spec:
  rules:
    - host: {{ .Values.apiserver.advertise.internal.ingress.hostname }}
      http:
        paths:
          - path: ''
            pathType: ImplementationSpecific
            backend:
              service:
                name: apiserver
                port:
                  number: 443