kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: apiserver
  annotations:
    route.openshift.io/termination: "passthrough"
spec:
  rules:
    - host:  {{ .Values.apiserver.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apiserver
                port:
                  name: https 
