apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler
  labels:
    app: kubernetes-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-scheduler
  template:
    metadata:
      labels:
        app: kubernetes-scheduler
    spec:
        containers:
          - name: kube-scheduler
            image: {{ .Values.registry }}/{{ .Values.repository }}/kube-scheduler:{{ .Values.version }}
            command:
                - kube-scheduler
            args:
                - "--bind-address=0.0.0.0"
                - "--leader-elect=true"
                - "--authentication-kubeconfig=/etc/kubernetes/scheduler/kubeconfig.conf"
                - "--authorization-kubeconfig=/etc/kubernetes/scheduler/kubeconfig.conf"
                - "--kubeconfig=/etc/kubernetes/scheduler/kubeconfig.conf"
                - --requestheader-client-ca-file=/etc/kubernetes/kubernetes-ca/tls.crt
                #- --requestheader-allowed-names=front-proxy-client
                - --requestheader-extra-headers-prefix=X-Remote-Extra-
                - --requestheader-group-headers=X-Remote-Group
                - --requestheader-username-headers=X-Remote-User
            ports:
              - containerPort: 10259
            volumeMounts:
              - name: kubeconfig
                mountPath: /etc/kubernetes/scheduler
                readOnly: true
              - name: kubernetes-ca
                mountPath: /etc/kubernetes/kubernetes-ca
                readOnly: true
            livenessProbe:
                failureThreshold: 8
                httpGet:
                  scheme: HTTPS
                  path: /healthz
                  port: 10259
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 15
        volumes:
          - name: kubernetes-ca
            secret:
                secretName: kubernetes-ca
          - name: kubeconfig
            secret:
                secretName: kubernetes-scheduler-kubeconfig
