apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-etcd-healthcheck-client
spec:
  secretName: kube-etcd-healthcheck-client
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: kube-etcd-healthcheck-client
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: etcd-ca