kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: konnectivity-server
  annotations:
    route.openshift.io/termination: "passthrough"
spec:
  rules:
    - host:  {{ .Values.apiserver.konnectivity.server.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: konnectivity
                port:
                  name: server
