apiVersion: v1
kind: Service
metadata:
  name: konnectivity
spec:
  selector:
    app: konnectivity
  ports:
    - name: server
      protocol: TCP
      port: 8131
      targetPort: 8131
    - name: agent
      protocol: TCP
      port: 8132
      targetPort: 8132
    - name: admin
      protocol: TCP
      port: 8133
      targetPort: 8133
    - name: health
      protocol: TCP
      port: 8134
      targetPort: 8134