apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-controller-manager
spec:
  secretName: kube-controller-manager
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "system:masters"
  commonName: kube-controller-manager
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: kubernetes-ca