apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-administrator
spec:
  secretName: cluster-administrator
  duration: 24h
  renewBefore: 12h
  subject:
    organizations:
      - "system:masters"
  commonName: cluster-admin
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: kubernetes-ca