apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-scheduler
spec:
  secretName: kubernetes-scheduler
  secretTemplate:
    annotations:
      cluster.kubeception.io/uuid: "{{ .Values.identifier }}"
      cluster.kubeception.io/address: "{{ .Values.apiserver.advertise.internal.ingress.hostname }}"
    labels:
      certificates.kubeception.io: "true"
      certificates.kubeception.io/kubeconfigs: "certificate"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - "system:masters"
  commonName: "system:kube-scheduler"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: kubernetes-ca