apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-apiserver
spec:
  secretName: kube-apiserver
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "kube-apiserver"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster
    - kubernetes.default.svc.cluster.local
    - {{ .Values.apiserver.konnectivity.agent.ingress.hostname }}
    - {{ .Values.apiserver.konnectivity.server.ingress.hostname }}
    - {{ .Values.apiserver.advertise.internal.ingress.hostname }}
    - {{ .Values.apiserver.advertise.public.ingress.hostname }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: kubernetes-ca