apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-service-accounts
spec:
  secretName: kube-service-accounts
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "kube-service-accounts"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: kubernetes-ca