apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-apiserver-external
spec:
  secretName: kube-apiserver-external
  dnsNames:
    - {{ .Values.apiserver.advertise.public.ingress.hostname }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.apiserver.advertise.public.ingress.issuer }}