apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: kube-controller-manager
  labels:
    kubeconfig.kubeception.io/server: "{{ .Values.apiserver.ingress.hostname }}"
    kubeconfig.kubeception.io/bootstrap: "true"
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""